export const NOISE_ANALYSIS_SLICE_SEC = 30;
export const NOISE_ANALYSIS_FRAME_MS = 50;
export const NOISE_SCORE_THRESHOLD_DBFS = -50;
export const NOISE_SCORE_SEGMENT_MERGE_GAP_MS = 500;
export const NOISE_SCORE_MAX_SEGMENTS_PER_MIN = 6;
export const NOISE_REALTIME_CHART_SLICE_COUNT = 1;
